### ISSUE TITLE
parallel run throw exception

### ISSUE THREAD

**Issue by Manasaanand** [camiloribeiro/cucumber-gradle-parallel#3]
Hi,

I did run your project through command prompt. Run inSequence runs without any issue but runinParallel throws error.

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':runInParallel'.
 at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)

**Comment by camiloribeiro** [comment]
Hi @Manasaanand. thanks again. I am really sorry you are having issues when trying it out. I just tried the latest master again and it is still working for me. 

My current environment is:
$ uname -an
Darwin Kernel Version 16.3.0 RELEASE_X86_64 x86_64

$ gradle --version

------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_74 (Oracle Corporation 25.74-b02)
OS:           Mac OS X 10.12.2 x86_64

$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

Let me know more details about yours. In parallel I will implement a docker way to avoid this kinds of issues from happening. Cheers!
